### ISSUE TITLE
Farming Calculator 

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/info_threefold#1]
We need to change the language on the Expected Returns sections.
We can't say we do x2 - x10 we could do x0.1 in reality. 

https://threefold.io/info/threefold#/threefold__farming_calculator

let's remove for now.

**Comment by despiegk** [comment]
I don't see that language?

**Comment by VonSub** [comment]
> I don't see that language?

<img width="1168" alt="Screenshot 2021-04-12 at 10 50 26" src="https://user-images.githubusercontent.com/29431263/114367664-f1ce2100-9b7c-11eb-93e4-c8b87d61d9f2.png">
