### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/info_threefold#10]
In the "Use ThreeFold" section a link does not work:

![image](https://user-images.githubusercontent.com/13766992/114501634-68315880-9c3b-11eb-9979-e08e8ef6c3cd.png)

This causes a black page.

This one produces an error:
https://threefold.io/info/cloud/cloud__evdc_marketplace/

**Comment by Sacha96** [comment]
fixed
