### ISSUE TITLE
Manual and Wiki on Vesting

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/info_threefold#10]
To improve the overall market situation for TFT, we are inviting TFT holders to vest their tokens. To facilitate the vesting, we are creating a portal website.
Now we need a wiki page that explains how to use the portal and provide background information on what happens to the vested funds.

The vesting schedule ist described here here: https://secure.threefold.me/sheet/#/2/sheet/edit/nIcZQiIpsJaM8TEHbGw1iSfI/

**Comment by gmachtel** [comment]
Already have a version in https://github.com/threefoldfoundation/info_foundation_archive/blob/development/src/token/how_to_vest/how_to_vest.md linking to https://github.com/threefoldfoundation/info_foundation_archive/blob/development/src/token/vesting_pool.md
