### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_threefold#10]
- [x] https://wiki2.threefold.io/#/tech/technology/readme (Titles)
- [x] https://wiki2.threefold.io/#/tech/technology/create_node (Getting the ThreeFold Chain Binaries)
- [x] https://wiki2.threefold.io/#/tech/technology/wallet (Throughout)
- [x] https://wiki2.threefold.io/#/tech/technology/tfchain_explorer (some links don't go anywhere, some are invalid)
- [x] https://wiki2.threefold.io/#/blog/internet-growing-wild (10x power savings)

**Comment by VonSub** [comment]
to be pushed asap

**Comment by VonSub** [comment]
confirm fix
