### ISSUE TITLE
how to buy/sell TFT 

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/info_threefold#108]
- [x] ReadMe file needs to be updated with new information (Kristof said he would handle)
- [x] Needs section on how to sell

**Comment by Sacha96** [comment]
Hey guys, there was already an issue about it last week so decided to add you to this for overview on organisational project 2.0.5. Let me know if I can help in any way. Should be able to.

**Comment by VonSub** [comment]
@samtaggart and myself reviewed and restructured the whole section to a more logic flow.
