### ISSUE TITLE
Remove / edit content

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_threefold#11]
- [x] https://wiki2.threefold.io/#/blog/tech-new-internet (link to AYS)
- [x] https://wiki2.threefold.io/#/blog/open-source-technology (link to IYO)
- [x] https://wiki2.threefold.io/#/blog/memorandum_of_understanding (change from Stela to Sabrina?)
- [ ] https://wiki2.threefold.io/#/tech/whitepapers/decentralized-system-does-not-exist-yet (Include Errors, I think)
- [x] https://wiki2.threefold.io/#/tech/whitepapers/grid_or_edge (last link on page should link to white paper on wiki, not on google docs)
- [ ] https://wiki2.threefold.io/#/tech/whitepapers/blockchain_dilemma (Include Errors, I think)

**Comment by VonSub** [comment]
To check includes after syncing again.

**Comment by VonSub** [comment]
pushing includes to a different issue, seems to be something up with them.
