### ISSUE TITLE
Update wiki favicon

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_threefold#115]

**Comment by VonSub** [comment]
checked with @xmonader how we could get this done as that's meta data

**Comment by maximilianrang** [comment]
The current favicon lacks an alpha channel and is displayed with a white background.

**Comment by VonSub** [comment]
> The current favicon lacks an alpha channel and is displayed with a white background.

I uploaded a transparent .ICO no idea. Probably shows up that way because docsify handles it like that.... not sure.
