### ISSUE TITLE
Go back to production setup

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/info_threefold#134]
as we are already far beyond testing phase of the new docisfy implementation, let's go back to the setup as regular.

wiki3 = can be shut down for now
wiki2 = fed from dev branch
wiki = fed from master brach

**Comment by hossnys** [comment]
This done by making wiki.threefold.io and sdk.threefold.io feed from master branch , and wiki3.threefold.io , sdk3.threefold.io feed from development branch.

**Comment by xmonader** [comment]
https://sdk.threefold.io
https://sdk2.threefold.io
https://wiki.threefold.io
https://wiki2.threefold.io
