### ISSUE TITLE
Main Wiki: Make reward section a  1-pager  [development_farmingrewards]

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/info_threefold#16]
Reward version 3
Information is so dispersed. 

Link:
 https://info.threefold.io/#/threefold__farming_logic3
 https://info.threefold.io/#/threefold__cpr
 
 Make sure to have one-pager that explains:  CPR reward + explaining the different types of farmer (with different CPR reward), Farming Reward Calculation, Cultivation Fee and Burning of TFT. 
 
 Aim is to make it quick to understand the whole reward mechanism

**Comment by VonSub** [comment]
What branch does this go on?

**Comment by VonSub** [comment]
nvm will create a branch for it myself.

**Comment by VonSub** [comment]
@andhartl already did a lot of groundwork and has a meeting K on this tomorrow. He will probably take a first stab at this over the weekend.
