### ISSUE TITLE
Get Node simulations into wiki

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/info_threefold#173]
Get 3 simulations for the farmer.threefold.io nodes.

- Worst case
- Middle case
- Best case

To link to from the page so people can get an idea about ROI and Incomen.

**Comment by sasha-astiadi** [comment]
hi @VonSub , what is the status now? this project is outdated. im trying to clean up, please move to the latest project if still valid / open.

**Comment by VonSub** [comment]
can close, however we still need an easy way to simulate the 3 node ROI's for all. (separate issue will be created for that soon)
