### ISSUE TITLE
default style = rust

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#23]
![image](https://user-images.githubusercontent.com/6021844/78501778-93968300-775d-11ea-9083-5d780555ffa5.png)

**Comment by PeterNashaat** [comment]
Rust is default theme .

<img width="826" alt="Screen Shot 2020-04-05 at 8 42 22 PM" src="https://user-images.githubusercontent.com/13523434/78507021-03b50100-777e-11ea-83b1-ac4386bf9375.png">
