### ISSUE TITLE
position towards public exchanges and token hype doc [development_nohype]

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#24]
- explain token is not product by itself
- explain exchanges (see last message to ambassadors)
- explain how we need defi to get enough traction for exchanges

**Comment by nbabenko** [comment]
Hey @Vilnite , cannot find this issue mentioned in [TFT threefoldfoundation/home#183](https://github.com/threefoldfoundation/home/issues/183), will you edit it so we do not loose this one?

**Comment by Vilnite** [comment]
Thank you @nbabenko 
Added to a Wikis story: https://github.com/threefoldfoundation/home/issues/182

**Comment by nbabenko** [comment]
For now we've added improved manuals to the forum and sharing it with all newcomers to receive feedback, specifically if there will be any questions or misunderstandings. 
https://forum.threefold.io/t/useful-guides-and-information-how-to-buy-and-trade-tfts/904

Regarding token section there is an update that is waiting merge, and then I will work on the following sections of the wiki:
https://github.com/threefoldfoundation/info_threefold/pull/66 (https://github.com/threefoldfoundation/info_threefold/issues/65)

**Comment by nbabenko** [comment]
I guess with https://info.threefold.io/info/strategy#/internet4__tft_fly it can be closed for now?
