### ISSUE TITLE
bring to section: press

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#24]
![image](https://user-images.githubusercontent.com/6021844/78501827-deb09600-775d-11ea-9064-bcad1581f186.png)

there are probably more things we can bring to press

**Comment by VonSub** [comment]
@PeterNashaat make a press section and link 10.1 Memorandum of Understanding under it please.

**Comment by hossnys** [comment]
added here : http://157.245.87.227:3000/docs/blog/memorandum_of_understanding.html

**Comment by VonSub** [comment]
confrimed
