### ISSUE TITLE
doc how will we create a carbon neutral cloud [development_carbonneutral]

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#26]
- use slides as used in freeflow or threefold masters (copy as picture)
- explain relation to tag
- link to energy savings doc
- its a full blown circular ecosystem thing we are building
- explain we will use a carbon exchange or maybe even build our own TFT to carbon credits

**Comment by Vilnite** [comment]
Please see: https://threefold.io/info/threefold#/threefold__carbon_negative
