### ISSUE TITLE
https in summary.md doesn work

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#27]
![image](https://user-images.githubusercontent.com/6021844/78502544-f558ec00-7761-11ea-83c4-7e7d86f3c7ea.png)

worst case create a page and then there put screenshot of website
and then link on screenshot and next to it to website

check that everywhere

**Comment by PeterNashaat** [comment]
Something like this ?
<img width="1337" alt="Screen Shot 2020-04-05 at 9 31 25 PM" src="https://user-images.githubusercontent.com/13523434/78508146-e8012900-7784-11ea-89d3-e2f1b2de28c5.png">

<img width="1337" alt="Screen Shot 2020-04-05 at 9 31 14 PM" src="https://user-images.githubusercontent.com/13523434/78508142-dd469400-7784-11ea-9750-ca4004963b4c.png">
