### ISSUE TITLE
links on page for blogs

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#28]
![image](https://user-images.githubusercontent.com/6021844/78502626-4ff24800-7762-11ea-856b-c449ebdda844.png)

put the links of the blogs on the page itself as well

**Comment by PeterNashaat** [comment]
links added .
<img width="922" alt="Screen Shot 2020-04-05 at 8 54 48 PM" src="https://user-images.githubusercontent.com/13523434/78507327-ba65b100-777f-11ea-9a07-b208efb84b3b.png">
