### ISSUE TITLE
our plan of execution for the next 6 months  + purpose chat [development_plan]

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#28]
- see the content already on the existing branch development_plan and improve there
- needs to show people how we will provide value over next months
- add https://secure.threefold.me/pad/#/2/pad/edit/zYPHXkrQ0X3x18fZ95TJsMy4/ to the wiki (how to use chat)

**Comment by nbabenko** [comment]
Hey Kristof, I was able to open and edit document being anonymous. Just wanted to let you know that if we put links like this anyone will be able to mess around with our content in the cryptpad documents without any authentication

**Comment by samtaggart** [comment]
I did a bit of editing and shot to AmaZix for their feedback and to understand their support.

**Comment by samtaggart** [comment]
https://github.com/threefoldfoundation/info_threefold/commit/3aa6236367f2266621a8e052e133774fae83574f

@despiegk chat post
