### ISSUE TITLE
team: screenshot from website & do link to website

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#29]
![image](https://user-images.githubusercontent.com/6021844/78502697-a3fd2c80-7762-11ea-95fe-d307582c87ff.png)

**Comment by PeterNashaat** [comment]
Images added and link to team page to threefold.io website
<img width="1227" alt="Screen Shot 2020-04-05 at 9 51 10 PM" src="https://user-images.githubusercontent.com/13523434/78508500-9c9c4a00-7787-11ea-91d3-4ea33c6fc709.png">
