### ISSUE TITLE
Vesting - Misleading information

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/info_threefold#3]
![image](https://user-images.githubusercontent.com/61866569/114066078-9ad5fc80-989b-11eb-9cf0-7481f9274fa0.png)

This information is misleading. It is the unlocking that starts in May. Vesting has already started.

**Comment by maximilianrang** [comment]
![image](https://user-images.githubusercontent.com/61866569/114067214-d91feb80-989c-11eb-99c5-3b8da7463576.png)
this needs to be corrected

**Comment by Sacha96** [comment]
@maximilianrang next time please add link to the file or copy paste the URL to help us go faster. Thanks. Please check. I removed info in 2nd picture and edited info of 1st picture.
