### ISSUE TITLE
Display uptime of TF Grid services 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/info_threefold#30]
All TF Grid core services should display uptime on the TF Farming Wiki. 

These services are:

- Zero Hub
- VDC Monitor
- VDC deployer testnet
- VDC deployer devnet
- Explorer
- Bootstrap
- 3Bot deployer tesnet
- 3Bot deployer mainnet
- 3Bot deployer devnet

Uptimerobot is used to monitor the uptime (PM for login credentials). We can brand it with TF logo in uptimerobot PRO plan if needed (we use free plan for now).

**Comment by sabrinasadik** [comment]
![118465109-d9b06b00-b701-11eb-8ebc-47fb17d1692f](https://user-images.githubusercontent.com/31733464/118991099-b98fde80-b983-11eb-81c4-eabde809aba3.png)

**Comment by Sacha96** [comment]
please define a branch for us to track and support

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/84
