### ISSUE TITLE
lets move all whitepapers in

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#31]
now in this mdbook, looks good enough

## once done

- lets move it all and remove the pdf's
- on the gdoc's put link to the published mdbook

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/78503121-e6c00400-7764-11ea-9091-5faa5a7a101a.png)

we need to check if the content not too far appart

please note there are include macro's in mdbook as well

**Comment by VonSub** [comment]
this applies to all Whitepapers we have? Tech & Foundation.

**Comment by VonSub** [comment]
@despiegk This will need some reviewing from your side still, but all of them are in.

Added all whitepapers I could find.
Already added 1 to _beta: stated it needed finishing
Already added 1 to _archive: seemed very redundant, added comment line.

[TOC] not working, need to see if we remove, add manually or makt it work
{anchors} also failing to work, same as above.

**Comment by VonSub** [comment]
To be done still:

- [ ] Put links in docs they came from
- [ ] Find fix for TOC shortcode (or remove TOC)
- [ ] Find fix for Anchors from TOC or remove 
- [ ] Write up README.md better/more
