### ISSUE TITLE
on central wiki server

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#32]
on a central 3bot server

- host all websites
- do a package for mdbook and let it refresh every 5 min
- do a github trigger to it so it lets pull git & reload mdbook

remove the old wiki stuff

**Comment by VonSub** [comment]
@PeterNashaat can you fill in here what has been done and please link to documentation.

**Comment by PeterNashaat** [comment]
we have 2 3bot servers 
1- staging : ```ssh root@157.245.87.227 -A```
2- production : ```ssh root@165.227.198.157 -A```

**Comment by rkhamis** [comment]
support for packages: https://github.com/threefoldtech/jumpscaleX_threebot/issues/544

**Comment by rkhamis** [comment]
we currently don't have support for githooks or refresh. we can do it, but it will take some time. please advice on how important that is

**Comment by PeterNashaat** [comment]
i will do corn job as  work a round for now

**Comment by PeterNashaat** [comment]
cron job is working now

**Comment by rkhamis** [comment]
issue to have packages: https://github.com/threefoldtech/jumpscaleX_threebot/issues/553.

I believe that the work on this issue regarding the packages should not be tracked here, so @VonSub please verify the setup @PeterNashaat deployed

**Comment by VonSub** [comment]
@rkhamis I will have to check how to do this.
