### ISSUE TITLE
Planet Positive Farming [development_planetpositive]

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/info_threefold#32]
**Description:**
For now we will push certified farming to later and go with minimum requirements as we can’t measure it for now like raised by @andhartl.
But we still need a model that brings trust and need it to already be aligned with freeflow.

**Deliverables**
- [x] Add new farming logic (see below) 
- [x] Add carbon offset logic for planet positive 
- [ ] Add max carbon consumption for planet positive 
- [ ] change all DIY & certified to Planet Friendly and Planet Positive

**New model:**
- Certified hardware > Planet Positive (PP) Node
- PP Node & Farmer leads to PP Internet capacity 
- So 2 types of Farming - DIY & PP

**Criteria to be met for PP Node:**
1. Energy (CO2 consumed by CU & SU)
2. Trust/ authenticity  (proof-of-authenticity = education)
3. Location/ Connectivity (more IPs, location-dispersed, e.g refugee camp, etc..)

_PP = energy + trust + accessibility_ 

**PP Farming advantages:**
- PP nodes get priority on the Grid as they consume less energy
- PP Farmers can do pull requests (PR) to our wiki (add farmer section to data_threefold) to add their details (we shouldn't do it - we only confirm PR) - only PP Farmers will be showcased
-- They are vocal about who they are, and why they do what they do, etc… 

**1. Energy Consumption**
- need a way to measure co2 consumed by SU & CU
- can be measured by a network of trust that verifies authenticity of information

**2. Proof-of-authenticity** 
- Information must be real/ authentic (not about ratings or skills, but by authenticity - either authentic or not - binary))
- We can verify this via peer reviews
- Easy way is to incentivize network growth
- You get proof of authenticity by educating other farmers (So as a farmer you become a teacher evaluated by your students)
- And these other farmers evaluate your farm (Review of authenticity every 6months or so)
- This creates a chain of trust 
- More students the better as it increases your authenticity rating
- The more the rating of authenticity you have, the faster you unlock tokens from staking

What we can do is aggregate voting: >> X 99 X 9 X 1 points
- e.g. I convince Adnan to become a farmer and authenticate me > I get 99 points
-- If Adnan convinces another person I get 9 points
--- If that person convinces another one to join I get 1 points

**3. Location**
- By bringing capacity to new regions you get more points (e.g. putting a node in Kakuma you get more points than building a data center)
- Also the more you disperse your node network the more points
- More IPs you provide to the network, the more points you get

We believe that such a system will ensure it is self-certified while rewarding the biggest contributors to the network.

This 33% of capacity needs to be there to unlock staking and by having more points and being ranked on top of Planet Positive Nodes you increase your visibility on the Explorer.

**Comment by andhartl** [comment]
that means if I do not have more than 1 internet connections I can not be a pp farmer? that's super non inclusive imho.

**Comment by andhartl** [comment]
summarised thoughts/ideas from a session with weynand:
<img width="1686" alt="image" src="https://user-images.githubusercontent.com/18591016/119321779-4d5ff400-bc7d-11eb-916c-b5af2a787c02.png">

**Comment by andhartl** [comment]
more details on the requirements see here: https://secure.threefold.me/sheet/#/2/sheet/edit/KmAAcWwgkQO0hJVhihL64KoX/

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/86
