### ISSUE TITLE
faq on tokens

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#33]
![image](https://user-images.githubusercontent.com/6021844/78503192-68179680-7765-11ea-9e03-dcb33fba7337.png)

**Comment by PeterNashaat** [comment]
image fixed
<img width="1021" alt="Screen Shot 2020-04-05 at 9 01 49 PM" src="https://user-images.githubusercontent.com/13523434/78507520-b9814f00-7780-11ea-988e-fc6168ce9f98.png">
