### ISSUE TITLE
Update navbar's background

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/info_threefold#34]
Navbar's background is uneven. Please make it consistent.

<img width="1440" alt="Screenshot 2021-05-24 at 21 38 15" src="https://user-images.githubusercontent.com/20182572/119386388-84172800-bcd8-11eb-9c3a-95bcb7bbe48a.png">

**Comment by samaradel** [comment]
@Vilnite  It works.. maybe you need to clear caches

![image](https://user-images.githubusercontent.com/11662805/119452789-0b938400-bd37-11eb-8125-ac85edfb0b78.png)
