### ISSUE TITLE
agile principles not visible & in menu

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#34]
![image](https://user-images.githubusercontent.com/6021844/78503247-c2185c00-7765-11ea-815d-3f8c079b4e7c.png)

**Comment by VonSub** [comment]
@PeterNashaat another on that needs including into the sidebar

**Comment by PeterNashaat** [comment]
Added
<img width="695" alt="Screen Shot 2020-04-06 at 4 09 34 PM" src="https://user-images.githubusercontent.com/13523434/78567487-0f0d3880-7821-11ea-9032-f6e961a57b7a.png">
