### ISSUE TITLE
Create / update BTC purchase part of the wiki

### ISSUE THREAD

**Issue by gmachtel** [threefoldfoundation/info_threefold#35]
Needs to contain following elements : 
- [x] Risks around transaction fees for withdrawal BTC
- [x] Explain that this BTC wallet is to be used as gateway in to TFT, not for general BTC storage
- [x] Disclaimer that we can't recover the private keys

**Comment by Sacha96** [comment]
please define a branch for the story

**Comment by sasha-astiadi** [comment]
also explain about the btc api from crypto anchor @gmachtel

**Comment by gmachtel** [comment]
https://github.com/threefoldfoundation/info_threefold/blob/btc_wallet/src/token/apps_wallets/threefold_connect_btc_asset_guide.md
