### ISSUE TITLE
tools in collab not visible

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#35]
![image](https://user-images.githubusercontent.com/6021844/78503261-e5dba200-7765-11ea-9f70-97675632d14e.png)

**Comment by VonSub** [comment]
Tool .MD needs to be brought to collaboration part of the wiki (include in sidebar)

**Comment by hossnys** [comment]
tools added here http://157.245.87.227:3000/docs/collaboration/freeflow_tools/index.html
