### ISSUE TITLE
create tools & collaboration in navigation

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#37]
![image](https://user-images.githubusercontent.com/6021844/78503645-45d34800-7768-11ea-83ab-866730c43cd4.png)

create tools & collaboration in navigation

**Comment by despiegk** [comment]
also agile principles & community

**Comment by VonSub** [comment]
@PeterNashaat seems we need to bring some things back to the sidebar. The files are there but not linked.

**Comment by PeterNashaat** [comment]
Added

<img width="518" alt="Screen Shot 2020-04-06 at 5 21 58 PM" src="https://user-images.githubusercontent.com/13523434/78575085-28b37d80-782b-11ea-8197-9cb1f9f53df7.png">
