### ISSUE TITLE
generation went wrong, please clean all up

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#39]
![image](https://user-images.githubusercontent.com/6021844/78523491-448a3580-77d1-11ea-97dd-429476f8f0a6.png)

make sure there is a generation example in root of repo so people don't make mistake

**Comment by VonSub** [comment]
Will need to figure our MDbooks before I understand this issue I think.

**Comment by PeterNashaat** [comment]
if you mean /docs/docs , this is how mdbook works 
it generate the html files in /docs/docs directory

**Comment by despiegk** [comment]
no peter this is absolutely not how mdbook works

**Comment by despiegk** [comment]
now look at serve.sh
should not use anything else

**Comment by despiegk** [comment]
also the .ignore was not properly filled in

**Comment by despiegk** [comment]
ive now cleaned up but please make sure everyone knows

**Comment by PeterNashaat** [comment]
ok i will
