### ISSUE TITLE
Link errors on carbon double win page

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/info_threefold#41]
Please see what is the correct info here and fix these link errors.
Not sure if it's by purpose removed or just an error. It's images around carbon calculations so important to make sure it's fixed appropriately and in line across other wikis.
See info_yottagrid wiki, file: cloud_units_carbon_negative.md that has same info.

<img width="1221" alt="Screenshot 2021-05-31 at 17 48 33" src="https://user-images.githubusercontent.com/20182572/120210856-ed4aee00-c238-11eb-8090-08b229833c88.png">

**Comment by Sacha96** [comment]
@Vilnite please confirm if fixed as i still can't run publish tools
