### ISSUE TITLE
lost content on collaboration

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#42]
http://localhost:3000/docs/collaboration/stories.html

please see what empty and lets find content back
history

or on filesystem on other name

**Comment by hossnys** [comment]
lost content restored  , and now it's there :
http://157.245.87.227:4000/docs/collaboration/stories.html
http://157.245.87.227:4000/docs/collaboration/story_pitfalls.html

**Comment by VonSub** [comment]
confirmed

**Comment by VonSub** [comment]
confirmed
