### ISSUE TITLE
choose smaller names for menu items (left section)

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#47]
![image](https://user-images.githubusercontent.com/6021844/79228447-bf062580-7e61-11ea-8500-08f2e06eb91d.png)

and put some picture in  each whitepapers on top (or graphic)
so looks nicer finished

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/79228542-e6f58900-7e61-11ea-8a0f-a25f154e8020.png)

**Comment by VonSub** [comment]
outdated issue as we moved away from mdbooks
