### ISSUE TITLE
Add: How to configure your own 3Node? [development_doityourself]

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/info_threefold#49]
Description:

Informaiton on how to boot any hardware with zero os is hard to find at the moment. we need this in main wiki farming.

Deliverables:
- [x] add page on farming section 
- [x] descripe a-z process on how to boot any amd/ intel hardware with zero os 
- [x] produce video that walks people through the guide while setting up and farm and node

**Comment by andhartl** [comment]
on it with weynand.

**Comment by andhartl** [comment]
description already done a while ago. need to make it easier to find though: https://wiki.threefold.io/#/threefold__farming_diy_guide

Need to change the title to 'How to setup your own farm and node(s)'

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/18591016/120920400-d4ba5800-c6be-11eb-83c9-09d1685f91d7.png">

**Comment by weynandkuijpers** [comment]
- [ ] Video produced and shared with the promotion team.
- [ ] Description document with text and URLs created )https://secure.threefold.me/pad/#/3/pad/edit/a1f0f6bf2735cfc3f9735a462faceb31/)
- [ ]  Also - there is a good piece of information posted in the forum: https://forum.threefold.io/t/diy-nodes-guide/837.

**Comment by weynandkuijpers** [comment]
@Sacha96 is all looking good to get this published - then we can close the issue.

**Comment by weynandkuijpers** [comment]
All done - issue closed
