### ISSUE TITLE
Add StellarX exchange to the list of exchange

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/info_threefold#5]
https://www.stellarx.com/markets/TFT:GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47

StellarX is a UI for stellar DEX, lets add it to the wiki manual. You can trade there and also you can keep tokens there.

**Comment by samtaggart** [comment]
I think there is some StellarX content already on the wiki. Please coordinate with @Sacha96 !

**Comment by Sacha96** [comment]
btw, on StellarTerm TFT is not available. @nbabenko did they get back to you yet?

**Comment by Sacha96** [comment]
removed stellarterm @nbabenko . please check with them if we can add tft there and if they do create a new issue.
