### ISSUE TITLE
Improve How to Buy TFT section

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/info_threefold#50]
It's still a bit confusing here and there, please improve explanations on wiki how to get TFT. Don't focus on Selling just Buying.
- [ ] create a new working branch on main wiki: how_to_buy_tft_update

Focus on clearly explaining these main 3 ways for now:
- [ ] BSC to TFT in TF Connect (double check but looks good)
- [ ] XLM to TFT in Stellar (need to update page with clearer instructions)
https://threefold.io/info/threefold#/threefold__tft_stellar_dex
- [ ] BSC / Pancake Swap : What do I exchange to TFT here? BSC? BNB? not clear. Can you please improve this page?https://threefold.io/info/threefold#/threefold__tft_binance_defi

**Comment by nbabenko** [comment]
For now we've added improved manuals to the forum and sharing it with all newcomers to receive feedback, specifically if there will be any questions or misunderstandings.
https://forum.threefold.io/t/useful-guides-and-information-how-to-buy-and-trade-tfts/904

Regarding token section there is an update that is waiting merge, and then I will work on the following sections of the wiki:
Pull Request: #66 (Issue #65)
