### ISSUE TITLE
Vesting: what are we doing when the TFT price never hits 10cents USD

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_threefold#56]
we did not specify what happens when the tft price never goes over 10 cents.
suggest to invest after 12 month no matter what the tft price is doing.

we should also clearly state the 10 cent hurdle

**Comment by nbabenko** [comment]
agree, good point. support your suggestion

**Comment by nbabenko** [comment]
https://circles.threefold.me/project/despiegk-team_tf_marketing_communication/issue/48
