### ISSUE TITLE
farming info update [development_farming_update]

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_threefold#57]
- [ ] page for the newest titan update
    - [ ] https://info.threefold.io/#/tftech__titan_v2
- [ ] there was a new version of the calculator, that has not been uploaded (community add on - https://secure.threefold.me/sheet/#/2/sheet/edit/5HGrE2ptaRjYZS0Aqjv1huv5/)
- [ ] the farming calculation needs to be updated with screenshots of the new calculator and for the new box
- [ ] read the content again, see why people don't see the return because the return is huge
- [ ] create a question on forum, about farming return is too low, write answers why not and point to the wiki docs
- [ ] if there was a new box, make sure there is a page for it too (the bigger one roel is looking at)

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/88
