### ISSUE TITLE
Token: Get Technical detail written up

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/info_threefold#6]
- talk to Geert about this.

**Comment by VonSub** [comment]
- [ ] Atomic Swaps
- [ ] Proof of Blockstake
- [ ] BCDB & It's role in our architecture (show we're not just another BlockChain company running on another project's infrastructure)
- [ ] Stellar Dex (?)
- [ ]

**Comment by VonSub** [comment]
Had a call with @gmachtel just now, he'll start the documentation process ahead of our go-live on Stellar.

**Comment by despiegk** [comment]
where are the docs?
please provide links

**Comment by gmachtel** [comment]
Struggling a bit what is expected here: 
- atomic swaps is technology that was in Rivine/TFchain, but Stellar uses other method (assetcodes are all on the same blockchain)
- proof of blockstake is the Rivine consensus, so no longer relevant to me
- BCDB is described in architecture, but it's not a technology for payment and tokens, so not the right place. 
- Stellar Dex is described in https://github.com/threefoldfoundation/info_tfgridsdk#src/4_tokens/different_tokens/tft_stellarx.md
