### ISSUE TITLE
Feedback Farming Section on Wiki & Open Questions

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_threefold#60]
- [ ] We need a new version for v3 which shows burning and different cultivation split.
<img width="981" alt="What i Farming" src="https://user-images.githubusercontent.com/18591016/123289602-45fc6680-d519-11eb-80e1-e5561c92190d.png">

- [ ] Why do we use the word mining? We always said we are greener, … different then any of the other companies.
<img width="243" alt="Farming" src="https://user-images.githubusercontent.com/18591016/123289662-53195580-d519-11eb-93d6-cf29ce071de1.png">

- [ ] Shouldn’t CU earn more than SU?
<img width="1045" alt="cloud units are the base o measurement" src="https://user-images.githubusercontent.com/18591016/123289717-5e6c8100-d519-11eb-9e0a-e682238412ac.png">

- [ ] Not sure about the NU price?

- [ ] What about IPV4 remuneration?

<img width="1031" alt="Proof-of-Utilization" src="https://user-images.githubusercontent.com/18591016/123289804-704e2400-d519-11eb-9a1b-3105a1932685.png">

- [ ] We say 10-50%
But here up to 75%. What is the right one to mention?
<img width="722" alt="When capacity bought by Certified Sales Channel" src="https://user-images.githubusercontent.com/18591016/123289866-7d6b1300-d519-11eb-95df-2b533948f71b.png">

- [ ] Where is the margin for TF tech?

- [ ] We are not ready for V3 minting. Would start August to buy us time. So all the new tv2.1 people will already be v3 (delivery will not be before aug).
(2 or 3) is also confusing. People will not understand.
<img width="994" alt="Steps To Becoming A Farmer" src="https://user-images.githubusercontent.com/18591016/123290027-9c69a500-d519-11eb-9212-a128ac99ed41.png">

- [ ] Three consecutive	 month or random?
<img width="996" alt="Staking of Farmed TFT" src="https://user-images.githubusercontent.com/18591016/123290082-a68ba380-d519-11eb-9f6b-b461f2bf0902.png">

- [ ] Should say until July 2021 incl.
<img width="921" alt="Providing hardware reliably is rewarded with a certification that leads to increased earnings in TET for certified farmers" src="https://user-images.githubusercontent.com/18591016/123290122-b1463880-d519-11eb-9903-7b5a9619a498.png">

- [ ] Is it certified farming or farming with a certified node?
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/18591016/123432111-b1eed580-d5d2-11eb-9f77-374bfa49eb57.png">

**Comment by andhartl** [comment]
NU is per GB not per month, right?

<img width="948" alt="image" src="https://user-images.githubusercontent.com/18591016/123556053-d80ea400-d791-11eb-8abb-842707d7d795.png">

<img width="943" alt="image" src="https://user-images.githubusercontent.com/18591016/123556070-ec52a100-d791-11eb-92b2-a202c2f03700.png">

**Comment by weynandkuijpers** [comment]
Further to this two suggestions were made by "Crypton" from the community

1. To attract interest from the crypto community to start farming and contribute to the grid the token "acquisition" is too slow.  It's too slow in a number of ways:
       -  monthly minting.  You only see the result of what you farm at the end of the rmonth?  Proof oc capacity and creating a stable grid is important but in this fast moving economy waiting for a month to see the result is long
       - **suggestion**:  Make a category (DIY?} that gets weekly their tokens deposited.
2. the 2 year staking / 30% rule is also not helping to attract people from the crypto world (even when they like the project).  the 30% utlisation trigger should happen way before the 24 monts marker but it;s unclear how that is being calculated.
      - is it  (30% CU && 30% SU)
      - is it (30% CU || 30% SU)
      - and how does the NU utilisation come into play.  if only 10% of the storage is utilized but very intensely used (AI, datalake, other intense use cases) can network usage accelarate the 30% trigger?

**Comment by weynandkuijpers** [comment]
![image](https://user-images.githubusercontent.com/13766992/123912233-d4e00780-d98d-11eb-9188-c95d94b78f28.png)

Image is from [here](https://wiki.threefold.io/#/threefold__farming_reward?id=proof-of-capacity)

Network farming does not make sense to me.  For CU / SU  is a simple multiplication of how many CU you provide and the amount of TFT being rewarded per Unit.   Unit being a cerain amount of hardware.  For network we now include "network" usage in the farming part of the rewards and 0 reward in the revenue (consumption) part of the grid.  Wjy are we mixing "providing and proving utlity to be available" and "utility consumption.

also - 1GB of transfer in a month = 1E9 bytes per month = 1E9 / 30 / 24 / 60 / 60 bytes per second = 385 bytes / second = 3kb/s average throughout the whole months.  This provides you with 0.2 TFT / months.  

so for a steady 3mbps stream you get 0.2 * 1000 -> 200TFT, 30mbps get you 2000TFT/monrh.  This is way better than any of the hardware faming.  Is this what we want?

**Comment by weynandkuijpers** [comment]
- [ ] When you hit 30% is that the trigger to receive all of you token from that point on in your wallet, or - when you dip back under 30% utilization do your tokens end up being staked again?  I got this question from the community and did not find a definitive answer to it.

**Comment by andhartl** [comment]
- [ ] TB or GB?
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/18591016/124431043-32020180-dd70-11eb-999a-b60be8fee0c2.png">

**Comment by andhartl** [comment]
-  [ ] move to September?

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/18591016/124431728-0895a580-dd71-11eb-8729-854e06a52f85.png">

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/89
