### ISSUE TITLE
pull latest master update about release notes

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/info_threefold#61]
release notes not showing up after merged to master https://wiki.threefold.io/#/release_mgmt

files on master:
https://github.com/threefoldfoundation/info_threefold/blob/master/src/release_mgmt/release_mgmt.md

please pull to the latest version thank you

**Comment by hossnys** [comment]
@sasha-astiadi  publishingtool is using branch development for all wikis and websites so please merge your changes to development branch so we can put it on staging to be reviewed then pushed to production .

**Comment by sasha-astiadi** [comment]
@hossnys changes from master has been brought to dveelopment

**Comment by hossnys** [comment]
there was a broken link which is fixed [here](https://github.com/threefoldfoundation/info_threefold/commit/25498c6e22931699d979084dec110bf0329172a9) and it's now live here https://wiki.threefold.io/#/release_mgmt
