### ISSUE TITLE
Clear out wiki errors

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/info_threefold#67]
Bunch of errors that needs to be cleared

<img width="1430" alt="Screenshot 2021-07-06 at 08 44 50" src="https://user-images.githubusercontent.com/20182572/124548485-73f57b00-de36-11eb-9b00-f87306044b18.png">

- [x] strategy
- [x] internet4
- [x] main wiki
- [x] sdk

**Comment by Sacha96** [comment]
Can we get a status quo on this one?

**Comment by Vilnite** [comment]
Pretty much all errors are cleared out from wikis listed in the issue.
There were few that I didn't feel equipped to fix atm, like links to quantumsafestorage wiki (on main wiki), or some includes in public wiki from private one, like strategy or funding.
