### ISSUE TITLE
Update Definitions for DIY, Certified and Managed Capacity

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_threefold#68]
Update and leave managed out as we do no longer need it
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/18591016/124560256-e5382c80-de3c-11eb-98a7-93c4b94a02c2.png">

**Comment by Vilnite** [comment]
See in circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/90
