### ISSUE TITLE
Typo in Buying & selling ThreeFold Tokens (TFT) page

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldfoundation/info_threefold#7]
https://wiki.threefold.io/#/how_to_buy_and_sell

From public exanges ==> From public exchanges

![Screenshot from 2021-03-02 16-32-55](https://user-images.githubusercontent.com/16083592/109663601-f9111080-7b74-11eb-8826-217fa1dc80ec.png)

**Comment by samtaggart** [comment]
I've reworked this whole page locally, it just needs to be pushed to production. :)
