### ISSUE TITLE
Adding information to Vesting - Why Vest?

### ISSUE THREAD

**Issue by down2basics** [threefoldfoundation/info_threefold#7]
We can add the reasoning for Vesting:

Link: https://threefold.io/info/threefold#/threefold__vesting_overview

Is Vesting right for me?

If you are an ardent believer in the ThreFold Project and you see the long-term value, then the answer should come to you fairly easily. By Vesting your TFTs you give a vote of confidence to the project as this will reduce the supply of tokens and let the token ecosystem grow organically. We do not believe in meddling with the natural course of demand and supply and hence we have made the vesting scheme voluntary. 

If you are in for the long run, then by vesting your tokens (which you were probably going to hold on to in the long run anyway) you basically say I am not going to sell my tokens at the current price. Instead of keeping this knowledge to yourself you announce it to the world.

**Comment by Sacha96** [comment]
Added it to vesting_pool https://github.com/threefoldfoundation/info_threefold/blob/development_token/src/token/vesting/vesting_pool.md

@despiegk @down2basics please have a look, thanks
