### ISSUE TITLE
Update Certification Requirements

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/info_threefold#70]
From this link:

https://threefold.io/info/threefold#/threefold__certified_farming

we link to: 
https://threefold.io/info/threefold#/threefold__farming_certified_requirements_

These requirements need to be updated asap as no one farming from home is probably able to meet the requirements.
We need to:
- [ ] Define the requirements
- [ ] Update the info
- [ ] Shoot it out to the public that is' been updated.

**Comment by andhartl** [comment]
there needs to be a clear description what a home farmer and a datacenter farmer has to fulfil. things like 99.5% uptime, two isps and a foxed IP address are a not possible for home farmers. would go for 97% which means almost 24h downtime and should be doable for any homy.

**Comment by Vilnite** [comment]
See in circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/91
