### ISSUE TITLE
Update Grid Info in tech overview 

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/info_threefold#73]
![IMAGE 2020-05-02 12:13:45](https://user-images.githubusercontent.com/54844940/80861352-5f37b900-8c6e-11ea-9371-1835ada8a4a5.jpg)

We need to remove/change this to keep our info consistent. just a fyi. In technology overview whitepaper

**Comment by weynandkuijpers** [comment]
Update the picture with a more recent version which no longer has specific information on farmers in.
