### ISSUE TITLE
Planet Positive Farming: Amount of TFT reallocated to offset Carbon Footprint 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/info_threefold#74]
**Description:** 
One of the organizational KPIs is "proof of business model". TAG will be the partner that will help in proving our Planet Positive Farming business model. 

We need to have a section/doc in Wiki that shows the amount of TFT per month that will be reallocated to Take Action Global for Carbon Offsetting. 

**To do:** 

- [ ] Calculation of the amount of TFT to be reallocated to TAG 
- [ ] Stakeholder Approval 
- [ ] Incorporated in Wiki - Planet Positive Farming

**Comment by andhartl** [comment]
amount of tft to be allocated to tag is in the simulation: https://secure.threefold.me/sheet/#/2/sheet/view/fHBNDO5eW4ZrwJnLNTAlj2VsuQDCbJE7qeyuwjC-FWM/

@AlexandreHannelas pls check if enough to make pp farming work.
note: file has been changed. pls wait until its back working

**Comment by andhartl** [comment]
currently it is 1tft per cu and su per month. not sure if this is sufficient enough.
<img width="961" alt="image" src="https://user-images.githubusercontent.com/18591016/125437266-371e6919-7811-4c9a-90de-fc61da4a0482.png">
@AlexandreHannelas do those numbers help you to calculate?

**Comment by AlexandreHannelas** [comment]
The spreadsheet in Numbers format. Please download the file and provide the feedback. 

https://drive.google.com/file/d/1Ibkgn4eqFOkgrz7okQ_OllKSDKXkil1Y/view?usp=sharing

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/93
