### ISSUE TITLE
SDK MANUAL - update all links existed on manual from manual.threefold.io to wiki.threefold.io

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/info_threefold#8]
<img width="863" alt="Screenshot 2021-03-15 at 15 06 10" src="https://user-images.githubusercontent.com/43240801/111166056-03350500-85a0-11eb-987f-d4a332828cbb.png">

for example on wiki https://wiki.threefold.io/#/farm_setup_management
the link on the .md file, referring to **'Farm Management & Setup'** is still going to https://manual.threefold.io/#/farm_setup_management instead of https://wiki.threefold.io/#/farm_setup_management

**Comment by samtaggart** [comment]
This is not actually correct, we need to be using [link text](filename) or [linktext](wikiname:filename) format. We shouldn't link to URLs when linking between wikis.
