### ISSUE TITLE
Cultivation Flow: Include 5% for TF Foundation if Farmer buys back its own capacity

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_threefold#83]
Split in 25% burning, 5% tf foundation, 70% farmer

see: https://www.google.com/url?q=https://info.threefold.io/%23/threefold__cultivation_flow&sa=D&source=editors&ust=1628519801451000&usg=AOvVaw0pxtynurFGfRvB-3b5V1gg

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/18591016/128716896-a7d21808-ad7c-4002-bcdf-b8b598932c45.png">

**Comment by despiegk** [comment]
should we do this?
in this case maybe TF Foundation should not have anything
this to make it more interesting for farmer to buy back?

**Comment by down2basics** [comment]
I think we should keep it 5% for the foundation across the board. If later we want to give an extra incentive to the farmer then the WC can decide and make exceptions.

**Comment by andhartl** [comment]
would show consistency over all scenarios of how to sell capacity. so yes 5%for foundation if farmer sells

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/95
