### ISSUE TITLE
Fix Github link on top-right corner of wikis (check all wikis)

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_threefold#84]
<img width="457" alt="Screen Shot 2021-08-10 at 10 49 58 AM" src="https://user-images.githubusercontent.com/50134479/128829441-5f79194f-3068-4981-b7b2-a189e97d46a3.png">

When clicking the blue Github cat, you get a 404 error on all of the wikis and I'm not sure exactly how to change it.

Please check all wikis and fix or explain how to fix and I can do it.

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/96
