### ISSUE TITLE
Farming Section: Core Grid Services that are needed by farmers

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_threefold#85]
Farmers need to adhere to certain SLAs (certified: 99.5%, diy: 97%. For them to make their SLAs possible grid core services need to be delivered in the same quality -> 99.5%
The ops team is working on migrating those services to a ha environment to guarantee the SLA of 99.5%.

The farming section in the wiki needs to state this.

suggestion for the text that needs to go into the wiki:

These are the core services ThreeFold farmers would need (a guarantee from ThreeFolf Foundation) to provide their SLAs towards TF Grid capacity users.
- [ ] TF Explorer: Global TF Grid 3Node and Gateway overview (https://explorer.threefold.io) -> will be decentralised with TF Grid 3.0
- [ ] TF Hub: Central and individual storage hub for flists (https://hub.grid.tf)
- [ ] TF Token Services: Services around TFT to make the TF Grid work
- [ ] 3Bot Deployer: Deploys 3Bot administrator in the TF Grid (https://deploy3bot.testnet.grid.tf/)
- [ ] 3Bot operations (both on-grid and off-grid - local SDK - deployments)

The following services are instrumental in the operating and expansion of the grid but not instrumental in delivering grid services. 
 Services that are contributing but not crucial:
- [ ] TF Connect: Authentication and wallet (for both the Farmers and capacity consumers)
- [ ] TF Bootstrap: Generates bootable images for 3Nodes (https://bootstrap.grid.tf).  Important for grid expansion but not grid operations.

All services below need to have an SLA of 99.5%.

See this dashboard for historic and current SLAs.

**Comment by weynandkuijpers** [comment]
Largely agree with the statement / proposal.   Some remarks implemented.  We have to make a distinction between what is needed to **use** the grid and what is needed to **operate/expland** the grid.

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/97
