### ISSUE TITLE
Fix include and missing link errors on wikis related to Internet4 and Legal

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_threefold#86]
Noticing a lot of errors with includes and missing links. It seems to be related to Internet4 wiki being down and an issue with the legal wiki.

Examples:

- Internet 4 wiki is down
- https://threefold.io/info/threefold#/ (missing image)
- sidebar (!!!include:carbonwin_sidebar)
- https://threefold.io/info/threefold#/threefold__grid_pricing (include error)
- https://wiki.threefold.io/#/internet4__technology & whole technology section (not found)
- https://threefold.io/info/threefold#/legal__legal (not found)

What needs to happen:

- [x] Find root of the issue
- [x] Fix the issue
- [x] Push to production

**Comment by Vilnite** [comment]
What about includes from main wiki? This is info_sdk

<img width="1546" alt="Screenshot 2021-08-16 at 18 49 56" src="https://user-images.githubusercontent.com/20182572/129600883-94404823-f5cf-4103-8977-f6956ed61e73.png">

**Comment by Vilnite** [comment]
Also error check on Gitpod is showing in HTML syntax. Can it be fixed?

<img width="1546" alt="Screenshot 2021-08-16 at 18 49 33" src="https://user-images.githubusercontent.com/20182572/129601118-cc2535d1-2a91-4ab7-8dbd-480510d92fc0.png">

**Comment by Vilnite** [comment]
So there's no technical bug, its about interlinking right wikis within repositories (see wiki_cofig file).
I'm fixing link errors as we speak.

See issue: https://github.com/threefoldfoundation/info_threefold/issues/67
