### ISSUE TITLE
Add all wikis to cofig folder

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/info_threefold#88]
Lots of, if not most, link errors shows due to includes and links from another wikis that are not listed in wiki_config folder.
 
<img width="1552" alt="Screenshot 2021-08-17 at 21 36 24" src="https://user-images.githubusercontent.com/20182572/129789910-6c060fc7-0747-48df-8d7f-46269579441c.png">

Wikis that are interlinked and missing in config folder (might be more, where can we find the whole wiki list now?):
- [ ] sdk
- [ ] strategy
- [ ] funding
- [ ] cloud
- [ ] queantumsafestorage
- [ ] accelerator
- [ ] twin

Can this be fixed so I can see the links and includes that really are broken and fix them?

**Comment by despiegk** [comment]
this is the full point, we should only include what is needed in there
are you telling that all above is used in main threefold website???
wow?

**Comment by despiegk** [comment]
Kristof De Spiegeleer, [18 Aug 2021 at 07:41:05]:
this is not bug

see my comment

we need to know which includes are needed

you can copy them from www_...private repo back into config

BUT WE NEED TO BE CAREFUL HERE

goal is not to include all, it just doesn't make sense if this happens

e.g. funding can rely upon threefold & internet4, but
threefold CANNOT rely on funding

same for most of the others

**Comment by Vilnite** [comment]
I've listed wikis that shows as broken includes on errors list for main wiki.
I'll start fixing it but we surely need to be more aware on where and how we use includes then as well.

**Comment by Vilnite** [comment]
Ok, as above is sorted more or less.

Errors show in HTML view by default to fix it to normal view every time I need to add # before /errors in url
like this : https://9998-aquamarine-ape-tffs3wmx.ws-eu15.gitpod.io/info/threefold/#/errors
instead of https://9998-aquamarine-ape-tffs3wmx.ws-eu15.gitpod.io/info/threefold/errors

it's very annoying. @hossnys can you fix this annoying thing with errors on code level?

**Comment by hossnys** [comment]
> Ok, as above is sorted more or less, there's still this:
> 
> Errors show in HTML view by default to fix it to easier view every time I need to add # before /errors in url
> like this : https://9998-aquamarine-ape-tffs3wmx.ws-eu15.gitpod.io/info/threefold/#/errors
> instead of https://9998-aquamarine-ape-tffs3wmx.ws-eu15.gitpod.io/info/threefold/errors
> 
> it's very annoying. @hossnys can you fix this thing on code level?

 @Vilnite the gitpod is not default way which we use to run our wikis and sites so we can't customize our code to run wikis on gitpod only , also adding # for now is not a big deal to worry about it , @MElborolossy if you have input here please do .
