### ISSUE TITLE
INFO TF: Make sure Liquidity Page is still accurate

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_threefold#9]
http://localhost:9998/info/threefold/#/threefold__token_liquidity

In info_foundation_archive repo

@maximilianrang or @nbabenko please check this to make sure it's all still accurate.

**Comment by samtaggart** [comment]
@Sacha96 checked this page in his review, closing this.

**Comment by samtaggart** [comment]
@Sacha96 reviewed this page but needs @despiegk to confirm if it's good.

**Comment by Sacha96** [comment]
Went through the page and for me all is accurate content.
