### ISSUE TITLE
Create guide on how to migrate from old app to TF Connect app

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/info_threefold#90]
Steps:

1. Download ThreeFold Connect App.
2. Create a new user profile.
3. Go to 'Wallet' and tap the + sign on the top right corner.
4. Insert a wallet name (can be anything, but only letters and no spaces).
5. Enter the 24-word security key.
6. Tap import wallet and wait.

Please keep in mind that without the correct security key, the tokens can not be retrieved.

**Comment by sabrinasadik** [comment]
Let me know if you'd like a video (screen recording) of this.

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/98
