### ISSUE TITLE
Sidebar Manuals and Knowledge Base pages duplicated

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/info_threefold#93]
1. Open wiki: https://wiki.threefold.io/
2. Go to Knowledgebase page from the sidebar menu
3. Go to Manuals page from the sidebar menu
4. They lead to the same page, https://wiki.threefold.io/#/threefold__wiki_overview
Expected result: One of the links should be removed or fixed if it should lead to another page

**Comment by Vilnite** [comment]
See in circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/99
