### ISSUE TITLE
"Why" and "Why we do what we do" pages are duplicated

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/info_threefold#94]
1. Open wiki
2. Go to Why page
3. Go to "Why we do what we do" page
4. They both lead to the same page https://wiki.threefold.io/#/threefold__why_intro
Expected result: remove duplication or fix "Why we do what we do" link to the correct page

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/100
